-- Stadiums Table
CREATE TABLE Stadiums (
    stadium_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    stadium_name VARCHAR2(100),
    city VARCHAR2(50),
    capacity NUMBER,
    established_year NUMBER(4)
);

-- Coaches Table
CREATE TABLE Coaches (
    coach_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    nationality VARCHAR2(50),
    experience_years NUMBER
);

-- Referees Table
CREATE TABLE Referees (
    referee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    nationality VARCHAR2(50),
    experience_years NUMBER
);
