-- League Seasons Table
CREATE TABLE LeagueSeasons (
    season_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    season_name VARCHAR2(50),
    start_date DATE,
    end_date DATE,
    champion_team_id NUMBER
);

-- Matches Table
CREATE TABLE Matches (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    home_team_id NUMBER,
    away_team_id NUMBER,
    stadium_id NUMBER,
    match_date DATE,
    league_season_id NUMBER,
    referee_id NUMBER,
    home_team_score NUMBER DEFAULT 0,
    away_team_score NUMBER DEFAULT 0
);

-- TeamPlayers Table
CREATE TABLE TeamPlayers (
    team_player_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    team_id NUMBER,
    player_id NUMBER,
    join_date DATE,
    leave_date DATE
);
